### ISSUE TITLE
Logic to specify the distribution is incorrect

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#106]
PlugIn L647. 
The logic to specify distributions is incorrect.  
Reads:  if (IgnitionDist == IgnitionDistribution.ZeroInflatedPoisson)

but it should read:
 if (IgnitionDist == IgnitionDistribution.Poisson)

based on the code that follows it.

**Comment by rmscheller** [comment]
Thanks, Melissa!
