### ISSUE TITLE
Model wants Landis.Library.climate-v4

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Extension-SCRPPLE#108]
The dependencies for scrpple in VS wants landis.Library.Climate-v4 and the PowerShell wants to download the dll for v4.1.

**Comment by rmscheller** [comment]
I am struggling to recreate this error.  PowerShell should be downloading v4.1.  The reference name and file name need not be identical:  https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/master/src/scrapple.csproj

I suggest going to C:\Program Files\LANDIS-II-v7\extensions and removing all climate library references and re-installing Scrpple.  There could be a versioning issue.

**Comment by rmscheller** [comment]
The problem was that support libraries were being downloaded in the src/ folder and they need to be in the src/lib/ folder.
