### ISSUE TITLE
Not all landscapes have Min RH, which can create negative values of landscapeAverageRH for ignitions 

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#113]
If you don't supply MinRH for your landscape, then RHmin=-99, and then landscapeAverageRelHumidity ends up being like -55.
landscapeAverageRelHumidity += weatherData.DailyMinRH[day] * climateRegionFractionSites;

So I'm proposing these code changes at L314 of PlugIn:
if (weatherData.DailyMinRH[day] == -99.0)
                            {
                                double relativeHumidity = AnnualClimate_Daily.ConvertSHtoRH(weatherData.DailySpecificHumidity[day], weatherData.DailyTemp[day]);
                                if (relativeHumidity > 100)
                                {
                                    relativeHumidity = 100.0;
                                }
                                landscapeAverageRelHumidity += relativeHumidity * climateRegionFractionSites;
                            }
                            else
                            {
                                landscapeAverageRelHumidity += weatherData.DailyMinRH[day] * climateRegionFractionSites;
                            }
                           // modelCore.UI.WriteLine("  Fire Weather Check Daily={0}, Average={1}", weatherData.DailyFireWeatherIndex[day], landscapeAverageFireWeatherIndex);
                        }

**Comment by mslucash** [comment]
Actually it's only used for Rx fire. And code will also need to be adjusted later in the code as well. 

![image](https://user-images.githubusercontent.com/7819936/104243903-33342080-5416-11eb-98d2-f19cf768ff95.png)

**Comment by rmscheller** [comment]
Thanks for the catch.  This was pushed to the upcoming release, v3.
