### ISSUE TITLE
Error after updating from v3.0 to v3.1 - "Could not initilize the actual year 0 from climate data"

### ISSUE THREAD

**Issue by tucker-furniss** [LANDIS-II-Foundation/Extension-SCRPPLE#123]
Hi,

I am getting the following error message when running SCRAPPLE v.3.1. I was able to run v3.0 without any errors. I updated from v3.0, and modified the scenario file accordingly. Are there any other edits to input files required to successfully transfer from 3.0 to 3.1?
I am getting the error when running the example model in the "TestLandscape" folder from the SCRAPPLE training in February (I am also getting the error message when running my own models). Error message from the landis-log is below.

Current time: 1
Running SCRAPPLE ...
   Processing landscape for Fire events ...
Internal error occurred within the program:
  **_Could not initilize the actual year 0 from climate data_**

Thanks,
Tucker

**Comment by rmscheller** [comment]
Tucker,

Did you try the posted example?  (Provided below the installer on the extension page.)  I can't guarantee older examples will still work.

**Comment by tucker-furniss** [comment]
I can't actually figure out how to download the Core7-SCRAPPLE3.1 folder, or any of its contents. Sorry for such a silly question, but my googling for answers has been a dead end. How does one download an example folder for testing?

**Comment by rmscheller** [comment]
Tucker,

Did you click on the link on the page at www.landis-ii.org/extensions?

**Comment by tucker-furniss** [comment]
Ah, got it. I was navigating to the example file in GitHub, I now see the DownGit links on the link at http://www.landis-ii.org/extensions. Thanks Rob. 

Unfortunately I'm getting the same error when running the example in the folder Core7-SCRAPPLE3.1. Same error message:

Current time: 1
Running SCRAPPLE ...
   Processing landscape for Fire events ...
Internal error occurred within the program:
  Could not initilize the actual year 0 from climate data

Stack trace:
   at Landis.Extension.Scrapple.PlugIn.Run() in C:\Users\rschell\Documents\LANDIS-Git\Extension-SCRPPLE\src\PlugIn.cs:line 257
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args) in D:\CGAProjects\Rob\LANDIS_FINAL\GitHubRepo\Core-Model-v7\Tool-Console\src\App.cs:line 99

**Comment by tucker-furniss** [comment]
One thing to note - I had to use the climate file from the 3.0 example, LTB_91_10.csv, because there wasn't a climate file provided for the 3.1 example. Just thought that may have something to do with it, as one of the updates to SCRAPPLE 3.1 was upgrading to the climate library v4.2.

**Comment by rmscheller** [comment]
Tucker,

I added the file.  I'm afraid you're one step ahead of me.  I haven't released 3.1 yet because it needs to be a coordinated release with NECN v6.7.

**Comment by tucker-furniss** [comment]
Copy that... I didn't realize that 3.1 wasn't officially released yet. Thanks Rob!
