### ISSUE TITLE
Request to let Rx fire spread naturally

### ISSUE THREAD

**Issue by tucker-furniss** [LANDIS-II-Foundation/Extension-SCRPPLE#127]
It appears that all Rx fire in SCRAPPLE is square, unless it is restricted by suppression. This renders the Rx fire functionality of SCRAPPLE unusable for my purposes. It would be great if users could let Rx fire burn naturally, following the same fire size and spread algorithms used for Natural and Accidental fires. It seems like this might be an easy tweak, since the spread algorithms already exist for other ignition types. This could be implemented as an option in the SCRAPPLE parameterization file, with a setting such as RxSpread = TargetRxSize OR SpreadAlgorithms.

Thanks for considering it!

**Comment by rmscheller** [comment]
Tucker,
It's a good idea!  The original idea was to ensure that Rx always reached it's target and therefore no limits to spread.  But that does create squares.  I'll take a look at the code... probably not too difficult.
Have you tried using stand maps?  

Charles,
Any inputs?  Good idea or bad?

Rob

**Comment by tucker-furniss** [comment]
Hi Rob, thanks for the response. Using stand ID to constrain Rx fire spread would work very nicely. I am using stand maps for the Biomass Harvest extension.

**Comment by rmscheller** [comment]
Tucker,

SCR* has its own stand maps.  It can use the Biomass Harvest maps, of course.  See section 2.38:  https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/master/docs/LANDIS-II%20SCRAPPLE%20v3.1%20User%20Guide.pdf

**Comment by tucker-furniss** [comment]
Ah, I wasn't aware of that! That should solve the square fire issue. Still might be nice to have the option to let Rx fire spread naturally, but I can also see the philosophy behind giving Rx fire a spread probability of 1 until it burns all of the target stand or max area. I'll close this for now, as I was mostly just trying to fix the square fires. Thanks for the quick help!
