### ISSUE TITLE
Error in FWI calcs

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#131]
Neil found and I corrected errors in DC and DMC in the climate library that have been present in the code likely since FWI was added to the climate library.  DC and DMC were additive between ecoregions, causing extremely high (cumulative) values of DC and DMC if you had more than one ecoregion in your landscape. This code bug was fixed in climate library version 4.3 so I recommend you compile Scrapple with this version of the climate library.

**Comment by ZacharyRobbins** [comment]
Hello!
When I ran this to compare the change, I found that the FWI index values coming from the climate library were pretty uniformly higher. Based on the above post I would have believed the opposite would occur. Am I mistaken on that?
Please see the quick comparison below. 
![image](https://user-images.githubusercontent.com/25291127/127341551-9195b890-059c-4d3f-a9ac-7420dd036599.png)

**Comment by mslucash** [comment]
I think the values for DC and DMC were so high that FWI was unresponsive to these parameters. With this change, I expect FWI to be much more responsive to DC. DMC and therefore climate, such that the values could be higher.

**Comment by ZacharyRobbins** [comment]
Thank you for clarifying.
