### ISSUE TITLE
Inconsistency in SpreadProbability betas

### ISSUE THREAD

**Issue by tucker-furniss** [LANDIS-II-Foundation/Extension-SCRPPLE#132]
Equation 5 in the SCRAPPLE user guide (both v3.0 and v3.1) defines B2 for spread probability as the coefficient for Effective Wind Speed: βx = β0 + β1(FWI) + β2(**EffectiveWindSpeed**) + β3(FineFuels)

However, the example input file indicates that the SpreadProbabilityB2 is for fine fuels. The current FireEvent.cs code seems to support the latter, but it isn't clear to me if the SpreadProbabilityB2 has always been for fine fuels, of if this was a recent change to the FireEvents.cs code. Could someone please confirm that SpreadProbabilityB2 is indeed for fine fuels, and update the user guide to fix this error? 

Many thanks,
Tucker

**Comment by ZacharyRobbins** [comment]
Thanks, Tucker! I can confirm that you are correct. I will work to update the error in the manual. Interested parties can see ln 527 in FireEvent.cs. I do not know when the change was made, I can't imagine it was changed recently, though the error may have been introduced in the manual in the last edits. Is there a particular need you have for when it changed? If so I can dig it out of the git log.

**Comment by tucker-furniss** [comment]
Thanks Zachary. I don't need to know exactly when it changed, just wanted to make sure that the version of SCRAPPLE I am running (v3.0.1) is the same. I assume it is - it looks like the last edit to that line was 3 years ago and the comments in the scrapple.txt initialization files are consistent (SpreadProbabilityB2 is for fine fuels) back through at least v2. I can't It appears that it has always been that way, and was perhaps just a typo in the user manual. Thanks for the quick response!
