### ISSUE TITLE
Initial state fuel maps from NECN

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Extension-SCRPPLE#133]
When running scrapple the initial fuel conditions are not added until the first NECN timestep. This can result in uncalibrated behavior prior to that step. We need to change the order of the assignment to fix this issue.

**Comment by ZacharyRobbins** [comment]
According to my latest runs, the fine fuels output is the same map at every time step, 24 year run.

**Comment by rmscheller** [comment]
I have updated the code with new v3.2.
