### ISSUE TITLE
Error in windspeed calculation in FireSpread R script

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Extension-SCRPPLE#137]
There is an error in the FireSpread R Script that is calculating effective windspeed incorrectly. Wind direction has been transposed with windspeed at some point. I will post a fix when able.

**Comment by rmscheller** [comment]
Has this been fixed yet?

**Comment by ZacharyRobbins** [comment]
Still active

**Comment by ZacharyRobbins** [comment]
Resolved. See commit a3d6c30364f14e890a2235485d150fc6bf6b54e7
