### ISSUE TITLE
Random ignition not tied to Random seed 

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Extension-SCRPPLE#138]
Ignition is currently tied to the Ether library, meaning it is not impacted by setting a random seed.  We'll need to make a branch that works with the Core random number generators to allow for quasi-deterministic runs for calibration.

**Comment by rmscheller** [comment]
Zachary, was this Tucker who requested the issue?

**Comment by ZacharyRobbins** [comment]
Yes

**Comment by rmscheller** [comment]
A new version 3.2.1 ready for testing.

**Comment by rmscheller** [comment]
Should be ready.  I wish I could add tucker-furniss to this conversation!

**Comment by tucker-furniss** [comment]
The issue appears to be fixed in v3.2.1. Setting a non-random seed in the scenario file will now produce the same fires. Thanks Zachary for posting about the issue and Rob for fixing it!
