### ISSUE TITLE
SCRPPLE freezing during first time step

### ISSUE THREAD

**Issue by alisondeak** [LANDIS-II-Foundation/Extension-SCRPPLE#139]
I'm running SCRPPLE v3.2 and NECN v6.8 and the batch file keeps freezing at timestep 1 (see attached screenshot). I've tried running it on two separate computers and have had the same issue on both. The scrpple-ignitions-log is being populated with ignitions and the scrpple-events-log is being populated with fires although the scrpple-summary-log is remaining empty. 

I'm unable to run earlier versions of NECN because this version of SCRPPLE requires the most recent version of the climate library.

Thank you, please let me know if you need additional information. 

![Screenshot 2021-11-30 084136](https://user-images.githubusercontent.com/80435299/144091200-c8c6f244-b09c-4edf-96f1-2b75e23fb644.png)

**Comment by rmscheller** [comment]
Allison, could you reply with the log file?

**Comment by rmscheller** [comment]
I suspect that there are too many ignitions per day.  Also send the ignitions-log (in addition to the general Landis-log).

**Comment by dirtyDeak** [comment]
I've attached the logs. Also, the scrpple-summary-log isn't populating, in case that's important information to know. 

Thanks Rob

[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/files/7748594/Landis-log.txt)
[scrapple-ignitions-log.csv](https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/files/7748596/scrapple-ignitions-log.csv)
[scrapple-ignitions-log.csv](https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/files/7748601/scrapple-ignitions-log.csv)

**Comment by rmscheller** [comment]
Alison,

Could you also send the scrapple-events-log?

**Comment by rmscheller** [comment]
Final request:  And a map of the study area.  Thanks!

**Comment by alisondeak** [comment]
Everything is attached. Thank you! Please let me know if you need anything else.

[scrapple-events-log.csv](https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/files/7792550/scrapple-events-log.csv)
[landscape_mask.tif.zip](https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/files/7792553/landscape_mask.tif.zip)
![Uploading landscape_map.png…]()

**Comment by alisondeak** [comment]
Happy new year Rob. Sorry I haven't been able to test this out sooner - I had a lot of issues connecting remotely to my desktop while traveling. Changing my ignition and spread probabilities has proved unsuccessful although I was able to run SCRPPLE on a subset of of my landscape (~200,000 cells) without any issues.

**Comment by rmscheller** [comment]
Alison,
Try the new installer, 3.2.1.  I added a max number of Rx attempts; in the event that it couldn't find an undisturbed cell.

**Comment by rmscheller** [comment]
Did you try the new installer?

**Comment by alisondeak** [comment]
It's running!
