### ISSUE TITLE
Fires during timestep one all high severity

### ISSUE THREAD

**Issue by alisondeak** [LANDIS-II-Foundation/Extension-SCRPPLE#142]
I'm using SCRPPLE v3.2.1 and all the fires ignited during timestep one (Rx included) are burning with a mean DNBR of 2000. This is consistent across several model runs. Example events log is attached.

Thank you!
Alison Deak

[scrapple-events-log.csv](https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/files/8402938/scrapple-events-log.csv)

**Comment by rmscheller** [comment]
Alison,
FYI:  This is the same issue as #140.

**Comment by rmscheller** [comment]
Alison,

See issue #140.  New release 3.2.2.

**Comment by alisondeak** [comment]
Awesome. Thanks Rob!

From: Robert Scheller ***@***.***>
Date: Thursday, May 5, 2022 at 9:07 AM
To: LANDIS-II-Foundation/Extension-SCRPPLE ***@***.***>
Cc: Alison Deak ***@***.***>, Author ***@***.***>
Subject: Re: [LANDIS-II-Foundation/Extension-SCRPPLE] Fires during timestep one all high severity (Issue #142)

Alison,

See issue #140<https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/issues/140>. New release 3.2.2.
