### ISSUE TITLE
Default fire shape should be a circle, not a square

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-SCRPPLE#149]

**Comment by rmscheller** [comment]
Diagonal spread should be multiple by 1/1.37

**Comment by rmscheller** [comment]
It seems we have already implemented this:  https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/master/src/FireEvent.cs#L255

So why still the squares?  More investigation required.

**Comment by ZacharyRobbins** [comment]
Could you provide me with further documentation of the problem? It seems like we already addressed this for all non-Rx fire? Is this issue specific to Rx fire?

**Comment by ZacharyRobbins** [comment]
The rasters are made of little squares; is that the problem? =)

**Comment by rmscheller** [comment]
It has recently popped up for Rx fire.  I dug into the code and it turned out that we were not using the circle adjustment for Rx fire and I turned that on.  Next I want to check to see if it's producing circles or some other shape.

**Comment by rmscheller** [comment]
OK, I hit a roadblock until we finalize NECN v7.  There is a version conflict within SCR* circle test I set up.  It will be super simple to test once that is resolved.

**Comment by ZacharyRobbins** [comment]
Is there any follow up I can do here?

**Comment by rmscheller** [comment]
The last I heard, circles were working correctly.  No more squares.  But I haven't had the opportunity to set up a test to see if they're perfect circles.  A test will require a landscape with no topography and uniform fuels.

**Comment by ZacharyRobbins** [comment]
Would you like me to set this up?

**Comment by rmscheller** [comment]
Let's first get input from @flakesw .  Sam, do you still see squares in CA?  (I'm not sure if this maneuver will add him to the thread...)

**Comment by flakesw** [comment]
I haven't been encountering squares, but I also haven't done any tests for that specifically
