### ISSUE TITLE
Percent slope treated as degrees in effective wind speed calculation

### ISSUE THREAD

**Issue by tgestabrook** [LANDIS-II-Foundation/Extension-SCRPPLE#153]
The SCRAPPLE documentation calls for the ground slope map to consist of "integer values representing percent slope on the 
ground", but the [function to calculate effective wind speed](https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/8732e42c4f9601e1a50b7d925a72904c6f3cb812/src/FireEvent.cs#L590C13-L590C122) converts from degrees to radians rather than percent to radians:

`double slopeRadians = (double)SiteVars.GroundSlope[site] / 180.0 * Math.PI; //convert from Degrees to Radians`

Apologies if the percent to degree conversion is made elsewhere and I missed it.

Cheers,
Thomas Estabrook

**Comment by rmscheller** [comment]
Thomas,

After reviewing the code, I'm sure you're right.  I'll update the documentation.
