### ISSUE TITLE
No mortality burns don't remove fine fuel or duff

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Extension-SCRPPLE#154]
In working with several new projects, we have discovered it is difficult to have "traditionally successful" Rx burns, in which the fuel loads are reduced, but cohort mortality is zero. In discussions with @rmscheller, Kate Jones and I found out that fuel load reductions are only triggered in NECN when cohort mortality occurs. 

I will shortly submit a pull request that will make any resulting fire remove 1 g of biomass, triggering partial mortality and removing fuels. 

Please place any comments in this thread or the subsequent pull request.

**Comment by rmscheller** [comment]
Z, you have Admin privileges, so you can directly commit.

**Comment by kejones8** [comment]
@rmscheller @ZacharyRobbins this seems to be a fix! I now have fuel reductions after every RX event.

**Comment by ZacharyRobbins** [comment]
@rmscheller I know, I issue this for posterity. And to remind myself to do it.
