### ISSUE TITLE
Need error message when 'ClimateFire' parameters are missing

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-SCRPPLE#33]
When using SCRAPPLE, the climate generator file has two new parameters

UsingFireClimate			yes
RelativeHumiditySlopeAdjust             77.68

However if you don't include those, it doesn't throw an error and just doesn't calculate FWI, hence no fires. We need an error message for when SCRAPPLE is turned on to alert users to the necessity of these new parameters

**Comment by ZacharyRobbins** [comment]
Bump

**Comment by rmscheller** [comment]
Zachary, I do not understand your message.

**Comment by ZacharyRobbins** [comment]
Sorry, I was drawing attention to this issue, which was never closed. We had discussed this problem in the last meeting, and I saw there was an issue for it. I was poking it, to draw it back to modernity.
