### ISSUE TITLE
Inconsistency in FWI

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#81]
The FWI in the future climate output file does not match the FWI in the events or the ignitions log file.  All 3 report different FWI for the same day/fire.

**Comment by rmscheller** [comment]
In the Ignition log, FWI = FWI, which is how the total number of ignitions across the entire landscape is determined.  It was mislabeled in the ignitions log file, now corrected.  In the Event log, FWI is the average for the entire fire event, not any particular day.  New installer (v2.1) now available on GitHub for testing.
