### ISSUE TITLE
Are Suppression Effectiveness Maps working properly?

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#82]
I set all my cells in my suppression maps to be zero, but I had a value >1 for my MeanSuprressionEffectiveness in the events log.  Why is that?  I thought if suppression was set to zero (i.e. no suppression), then event logs would also show a zero.

**Comment by rmscheller** [comment]
This was a log file issue.  Errors caused by inaccurate use of number of cells disturbed and reporting the inverted spread probability.  Will be fixed with next release.
