### ISSUE TITLE
Request for Dynamic Suppression

### ISSUE THREAD

**Issue by cgerstl** [LANDIS-II-Foundation/Extension-SCRPPLE#92]
The extension as currently written does not allow for dynamic suppression of fire over a model run.

**Comment by rmscheller** [comment]
Which type of suppression?  All three fire types?  Or just one or two?

**Comment by cgerstl** [comment]
For my purposes, all three, please.

**Comment by rmscheller** [comment]
Let's start with Accidental suppression maps, test and then build out from there.  See Line 116: https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/master/src/InputParameterParser.cs

**Comment by rmscheller** [comment]
Chris,
Did you test the new feature?

**Comment by cgerstl** [comment]
I did try it and it didn't seem to have any affect, but I think that's because the fires weren't spreading even before dynamically adding suppression. IIUC, suppression in Scrapple only affects spread, not ignitions.

I'll have to reparameterize my fire model to actually have spread and try again. I'll get back to you on this.

**Comment by rmscheller** [comment]
Chris, please send me the tests and accompanying documentation so that I can close this issue.  Thanks.

**Comment by ZacharyRobbins** [comment]
We were so close...

**Comment by ZacharyRobbins** [comment]
@rmscheller Do we have a status on this....

**Comment by rmscheller** [comment]
Uff, I lost that thread a while back.  I'll schedule some time to look through the code.

**Comment by rmscheller** [comment]
This has been implemented for Accidental Suppression.  See L226: https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/master/src/PlugIn.cs and L221: https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/master/src/InputParameterParser.cs

It has not been implemented for Lightning or Prescribed Suppression.  Nor has this been tested apparently.  It should be easy to add the other two ignition types.
