### ISSUE TITLE
Scrpple parameter for ZIPs

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Extension-SCRPPLE#95]
Need to rewrite the function implementing the zip model to ignition.

**Comment by ZacharyRobbins** [comment]
Code of interest is line 520-540 in PlugIn, I will return with the correction

**Comment by rmscheller** [comment]
Zachary, what is your proposed correction?  Also, how should we document changes in behavior?

**Comment by ZacharyRobbins** [comment]
I have not figured out how to create these variables, but the structure should be on line 594
I feel like I keep create variables that don't resolve this. Happy to do the code, but this is as far as I got. Any advice?


 double b0 = 0.0;
            double b1 = 0.0;
            if(ignitionType == Ignition.Lightning)
            {
                countb0 = Parameters.LightningIgnitioncountB0;
                countb1 = Parameters.LightningIgnitioncountB1;
                binomb0 = Parameters.LightningIgnitionbinomB0;
                binomb1 = Parameters.LightningIgnitionbinomB0;
            }
            //if (ignitionType == Ignition.Rx)
            //{
            //    b0 = parameters.RxFireIgnitionB0;
            //    b1 = parameters.RxFireIgnitionB1;
            //}
            if (ignitionType == Ignition.Accidental)
            {
                countb0 = Parameters.AccidentalIgnitioncountB0;
                countb1 = Parameters.AccidentalIgnitioncountB1;
                binomb0 = Parameters.AccidentalIgnitionbinomB0;
                binomb1 = Parameters.AccidentalIgnitionbinomB0;
            }

            int numIgnitions = 0;
            int BinomDraw = new Random().Next(0, 2);
            double alpha = Math.Pow(Math.E, (binomb0 + (binomb1 * fireWeatherIndex)));
            double zerosprob = alpha / (alpha + 1);
            if (BinomDraw <= zerosprob) {

                double possibleIgnitions = Math.Pow(Math.E, (b0 + (b1 * fireWeatherIndex)));
                int floorPossibleIginitions = (int)Math.Floor(possibleIgnitions);
                numIgnitions += floorPossibleIginitions;
                numIgnitions += (modelCore.GenerateUniform() <= (possibleIgnitions - (double)floorPossibleIginitions) ? 1 : 0);
            }
            else
            {
                numIgnitions = 0;
            }
            return numIgnitions;
        }


Second question: You can resolve the overestimation in the ignition by resolving the binomial zero probability in any given fit of the ZIPs model. I could provide a vignette if necessary.

**Comment by rmscheller** [comment]
(Note: Please include class name with line numbers.)

I created and committed 2.3.7, designed for testing the ZIP equations.  This is designed to be invisible to non-testers and therefore is not documented except below.

InputParameterParser.cs L170:  Format for the new inputs.  Note that the existing B0/B1 parameters will serve as the count parameter for now.  Maybe forever?

PlugIn.cs L611:  Where ZIP implemented if active.

Installer here: https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/tree/master/deploy/installer

**Comment by ZacharyRobbins** [comment]
In line 665 of Plugin.cs
int BinomDraw = new Random().Next(0, 2);
                double alpha = Math.Pow(Math.E, (binomb0 + (binomb1 * fireWeatherIndex)));
                double zerosprob = alpha / (alpha + 1);
                if (BinomDraw <= zerosprob)


BinomDraw may need to be a decimal, not an integer as zeroprob is a probability between(0,1). If Binomdraw is just either 0 or 1, then that draw would be the determinate, not the zero inflated portion.

 I may have that wrong, but I think that might be the discrepancy

**Comment by rmscheller** [comment]
Random.Next(int, int) returns an integer.  So, I'll recode as Random.Next(0,20)/10.0.  But then it isn't really a binomial draw.

Installer = 2.4.4.

**Comment by ZacharyRobbins** [comment]
Update 11/12: I added in the ZIPS function and it seems to be working for both ZIPS and classic Poisson.

**Comment by ZacharyRobbins** [comment]
Should still update the R code to reflect the two separate parameterization methods (Pois/ ZIPS).  I will wait until the pull is reviewed and then update so I can refer to the new Scrapple Input File.
