### ISSUE TITLE
No lightning ignition in Log. 2.4.1

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Extension-SCRPPLE#96]
Scrpple 2.4.1 
Lightning Ignitions do not appear to be stored in the ignitions log. I have lightning in the events log, killing trees, and all that. Yet each lightning ignition in the ignition log is zero.  Please see the images of logs.
Thank you,
-Zachary

![image](https://user-images.githubusercontent.com/25291127/92238964-375c9a00-ee88-11ea-95e5-492645d50f20.png)
![image](https://user-images.githubusercontent.com/25291127/92239021-50654b00-ee88-11ea-9486-214c1d22faf9.png)

**Comment by ZacharyRobbins** [comment]
Yes

**Comment by rmscheller** [comment]
Z, I found a bug, fixed that.  Also expanded IgnitionLog to include both AttemptedNumIgnitions and Actual.  This may or may not solve the problem.

**Comment by ZacharyRobbins** [comment]
Okay I should have the testing done by the end of the week

**Comment by ZacharyRobbins** [comment]
In the newest version, the new AttemptedNumIgnitions appear to always be zero, even if the Actual is a number.

**Comment by ZacharyRobbins** [comment]
![image](https://user-images.githubusercontent.com/25291127/93243874-d3bf5000-f756-11ea-9f2f-c5ebbb38c24f.png)

**Comment by ZacharyRobbins** [comment]
In line 665 of Plugin.cs
     int BinomDraw = new Random().Next(0, 2);
                double alpha = Math.Pow(Math.E, (binomb0 + (binomb1 * fireWeatherIndex)));
                double zerosprob = alpha / (alpha + 1);
                if (BinomDraw <= zerosprob)
BinomDraw may need to be a decimal not an integer as zeroprob is a probability between(0,1). If Binomdraw is just either 0 or 1, then that draw would be the determinate, not the zero inflated portion. I may have that wrong, but I think that might be the discrepancy

**Comment by rmscheller** [comment]
Zachary,
A rather obvious error.  Try installer 2.4.3.
