### ISSUE TITLE
Slope code comments and variable names are incorrect in FireEvent.cs.

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#97]
FireEvent.cs
L509. The comments say you are converting from Radians to Degrees, but you are doing the opposite. And your variable is named slopeDegrees when it should be slopeRadians.

double slopeDegrees = (double)SiteVars.GroundSlope[site] / 180.0 * Math.PI; //convert from Radians to Degrees

And I'm curious to know why slope has to be an int. Why?

**Comment by rmscheller** [comment]
Thanks for the corrections.  Why Vincent coded it that way, I do not know.

**Comment by rmscheller** [comment]
Comments and variable names corrected.
