### ISSUE TITLE
Relative humidity

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#98]
The latest version of the climate library allows not just Min/Max Relative Humidity, but also Average Relative Humidity and Specific Humidity. However, Scrapple only really allows for min RH (see L314 in PlugIn.cs). If minRH is null, then I think you should be able to use mean RH or mean SH to calculate landscapeAverageRelHumidity. Not everyone has access to min and max RH.

**Comment by rmscheller** [comment]
A good point.  We keyed that specifically to manager limits on prescribed fires and they use minimum relative humidity to determine whether to burn or not.  Can min RH be approximated from mean RH or SH?  This might be easier to handle from the user input end.

**Comment by mslucash** [comment]
I believe Min/Max RH are optional limits for Rx.  A quick fix would be an error message saying you can't use that limitation if you don't supply the variable. Right now it cycles through with very odd values (crazy high effective wind speed), which might have unforseen consequences on fire.

**Comment by rmscheller** [comment]
A good idea.

Do you need this for AK?  I can make the changes quick now or wait for next release.

**Comment by mslucash** [comment]
No I don't. I was looking through Scrapple to make sure my climate variables were being passed to Scrapple properly and noticed that they didn't work in Rx fire.
