### ISSUE TITLE
SiteVars

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#99]
I need these two statements (bolded below) added to SiteVars after Line 74 so I can access slope and aspect for DGS.

L73. PlugIn.ModelCore.RegisterSiteVar(SiteVars.TimeOfLastFire, "Fire.TimeOfLastEvent");
L74. PlugIn.ModelCore.RegisterSiteVar(SiteVars.GroundSlope, "Fire.Slope");
L75. PlugIn.ModelCore.RegisterSiteVar(SiteVars.UphillSlopeAzimuth, "Fire.Aspect");

![image](https://user-images.githubusercontent.com/7819936/97517367-4aed2400-1952-11eb-9466-7530a340360c.png)

**Comment by rmscheller** [comment]
I created a hotfix, here:  https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/AK-hotfix/deploy/installer/LANDIS-II-V7%20SCRAPPLE%202.4.5-AK-setup.exe

In general, I don't think disturbance extensions should feed base layers into succession extensions..  It creates an unnecessary dependency.   But given that we're using more and more slope/aspect data, we could either, a) add it to the scenario file for v8, or b) make it a required input via the succession library.
